settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: goAndGrpc
    path: .
    commands:
      install:
        status: true
        method: go build -o tmp/app.out src/main.go
      run:
        status: true
        method: tmp/app.out
    watcher:
      extensions:
        - go
      paths:
        - src/
      ignore:
        paths:
          - .git
          - .realize
          - vendor
          - build
          - scripts
