// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserBasicInfoRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBasicInfoRequest) Reset()         { *m = UserBasicInfoRequest{} }
func (m *UserBasicInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserBasicInfoRequest) ProtoMessage()    {}
func (*UserBasicInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_edb46576d227140f, []int{0}
}
func (m *UserBasicInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBasicInfoRequest.Unmarshal(m, b)
}
func (m *UserBasicInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBasicInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UserBasicInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBasicInfoRequest.Merge(dst, src)
}
func (m *UserBasicInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserBasicInfoRequest.Size(m)
}
func (m *UserBasicInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBasicInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserBasicInfoRequest proto.InternalMessageInfo

func (m *UserBasicInfoRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserBasicInfoRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserBasicInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBasicInfo) Reset()         { *m = UserBasicInfo{} }
func (m *UserBasicInfo) String() string { return proto.CompactTextString(m) }
func (*UserBasicInfo) ProtoMessage()    {}
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_edb46576d227140f, []int{1}
}
func (m *UserBasicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBasicInfo.Unmarshal(m, b)
}
func (m *UserBasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBasicInfo.Marshal(b, m, deterministic)
}
func (dst *UserBasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBasicInfo.Merge(dst, src)
}
func (m *UserBasicInfo) XXX_Size() int {
	return xxx_messageInfo_UserBasicInfo.Size(m)
}
func (m *UserBasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserBasicInfo proto.InternalMessageInfo

func (m *UserBasicInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserBasicInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*UserBasicInfoRequest)(nil), "UserBasicInfoRequest")
	proto.RegisterType((*UserBasicInfo)(nil), "UserBasicInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserInfoAPI service

type UserInfoAPIClient interface {
	GetUserBasicInfo(ctx context.Context, in *UserBasicInfoRequest, opts ...grpc.CallOption) (*UserBasicInfo, error)
}

type userInfoAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoAPIClient(cc *grpc.ClientConn) UserInfoAPIClient {
	return &userInfoAPIClient{cc}
}

func (c *userInfoAPIClient) GetUserBasicInfo(ctx context.Context, in *UserBasicInfoRequest, opts ...grpc.CallOption) (*UserBasicInfo, error) {
	out := new(UserBasicInfo)
	err := grpc.Invoke(ctx, "/UserInfoAPI/GetUserBasicInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserInfoAPI service

type UserInfoAPIServer interface {
	GetUserBasicInfo(context.Context, *UserBasicInfoRequest) (*UserBasicInfo, error)
}

func RegisterUserInfoAPIServer(s *grpc.Server, srv UserInfoAPIServer) {
	s.RegisterService(&_UserInfoAPI_serviceDesc, srv)
}

func _UserInfoAPI_GetUserBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBasicInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoAPIServer).GetUserBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserInfoAPI/GetUserBasicInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoAPIServer).GetUserBasicInfo(ctx, req.(*UserBasicInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfoAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserInfoAPI",
	HandlerType: (*UserInfoAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserBasicInfo",
			Handler:    _UserInfoAPI_GetUserBasicInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_user_edb46576d227140f) }

var fileDescriptor_user_edb46576d227140f = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x1e, 0x5c, 0x22, 0xa1, 0xc5, 0xa9,
	0x45, 0x4e, 0x89, 0xc5, 0x99, 0xc9, 0x9e, 0x79, 0x69, 0xf9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x22, 0x5c, 0xac, 0xa9, 0xb9, 0x89, 0x99, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x10, 0x8e, 0x90, 0x14, 0x17, 0x47, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04,
	0x13, 0x58, 0x02, 0xce, 0x57, 0x32, 0xe5, 0xe2, 0x45, 0x31, 0x49, 0x88, 0x8f, 0x8b, 0x29, 0x33,
	0x05, 0xaa, 0x9f, 0x29, 0x33, 0x05, 0x61, 0x24, 0x13, 0x92, 0x91, 0x46, 0x5e, 0x5c, 0xdc, 0x20,
	0x6d, 0x20, 0x1d, 0x8e, 0x01, 0x9e, 0x42, 0xd6, 0x5c, 0x02, 0xee, 0xa9, 0x25, 0xa8, 0x06, 0x89,
	0xea, 0x61, 0x73, 0xa2, 0x14, 0x1f, 0xaa, 0xb0, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x4f, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x00, 0x88, 0x7d, 0xe6, 0x00, 0x00, 0x00,
}
